import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import { Box, Button, Container, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, FormControl, FormLabel, InputLabel, MenuItem, Select, Snackbar, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useAccount, useBalance, useBlock, useBlockNumber, useReadContract, useReadContracts, useSimulateContract, useWriteContract } from 'wagmi';
import { ABI_CONTRACT, ADDRESS_CONTRACT } from '../utils/contractConfig'
import { parseEther, keccak256, toBytes, toUtf8Bytes, formatEther } from 'viem';
import { use, useMemo, useState } from 'react';
import { ToastContainer, toast } from 'react-toastify';
import useStakeBase from '../hooks/useStakeBase';
import { useGetPoolList } from '../hooks/useGetPoolList';
import { useRouter } from 'next/router';
import useGetERC20TokenInfo from '../hooks/useGetTokenInfo';
const ADMIN_ROLE = keccak256(toBytes("ADMIN_ROLE")); // 计算 ADMIN_ROLE 哈希值

const Home: NextPage = () => {
  const account = useAccount();
  const { data: currentBlockNumber } = useBlockNumber();
  const { startBlock, endBlock, rccPerBlock } = useStakeBase()
  const { data: isAdmin, isLoading } = useReadContract({
    address: ADDRESS_CONTRACT.RccStake,
    abi: ABI_CONTRACT.RCCStake,
    functionName: "hasRole",
    args: [ADMIN_ROLE, account.address], // 判断当前 address 是否有 ADMIN_ROLE
    query: {
      enabled: Boolean(account.address),
    },
  });
  const { poolList, fetchPoolList } = useGetPoolList();

  const stTokenInfoA = useGetERC20TokenInfo(ADDRESS_CONTRACT.TokenA);
  const stTokenInfoB = useGetERC20TokenInfo(ADDRESS_CONTRACT.TokenB);
  const rccTokenInfo = useGetERC20TokenInfo(ADDRESS_CONTRACT.RccToken)
  const mapTokenInfo = {
    [ADDRESS_CONTRACT.TokenA]: stTokenInfoA,
    [ADDRESS_CONTRACT.TokenB]: stTokenInfoB,
    [ADDRESS_CONTRACT.RccToken]: rccTokenInfo,
    [ADDRESS_CONTRACT.AddressZero]: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    }
  }

  const { writeContractAsync, writeContract, error } = useWriteContract();

  const poolData = useReadContract({
    address: ADDRESS_CONTRACT.RccStake,
    abi: ABI_CONTRACT.RCCStake,
    functionName: 'pool',
    args: [0],
  });

  const poolLength = useReadContract({
    address: ADDRESS_CONTRACT.RccStake,
    abi: ABI_CONTRACT.RCCStake,
    functionName: 'poolLength',
  });

  // console.log(poolData, "poolData")


  const handleAddPool = async (formData) => {
    try {
      await writeContractAsync({
        address: ADDRESS_CONTRACT.RccStake,
        abi: ABI_CONTRACT.RCCStake,
        functionName: 'addPool',
        args: [
          formData.stTokenAddress,
          formData.poolWeight,
          formData.minDepositAmount,
          formData.unstakeLockedBlocks,
          false
        ]
      })
      fetchPoolList()
      handleClose()
    } catch (error) {
      console.log(error, "error eeror")
    }
  }


  const [open, setOpen] = useState(false);
  const [defToken, setDefToken] = useState('');
  const handleClose = () => {
    setOpen(false);
  };
  // console.log(poolList, "poolList")
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <main>
        <Box sx={{ gap: '20px' }} minWidth='lg' >
          <Box sx={{ gap: '15px', display: 'flex', flexDirection: 'column', alignItems: 'center' }} >
            <Typography variant='h6' align='center' >
              Home Page Stake Infomation
            </Typography>
            <Typography variant='body2' align='center' >
              有效区块时间 {startBlock}  -  {endBlock} (当前链上最新区块{currentBlockNumber})
            </Typography>
            <Typography variant='body2' align='center' >
              每个区块获得的RCC奖励：{rccPerBlock}
            </Typography>
            <Typography variant='body2' align='center' >
              用户：{account.address}
            </Typography>
          </Box>


          <Box sx={{
            marginTop: '30px',
            border: '1px solid #eee',
            borderRadius: '12px',
            m: '30px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
          }} >
            {
              poolData.data ? <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }} >
                <Table>
                  <TableHead>
                    <TableRow>
                      <TableCell>
                        ID
                      </TableCell>
                      <TableCell>
                        代币
                      </TableCell>
                      <TableCell>
                        质押池的权重
                      </TableCell>
                      <TableCell>
                        开始区块号
                      </TableCell>
                      <TableCell>
                        结算区块号
                      </TableCell>
                      <TableCell>
                        每个质押代币累积的 RCC 数量
                      </TableCell>
                      <TableCell>
                        当前池中总质押代币量
                      </TableCell>
                      <TableCell>
                        最小质押金额
                      </TableCell>
                      <TableCell>
                        操作
                      </TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {
                      poolList.map((item: any, index: number) => {
                        return <TableRow key={index} >
                          <TableCell>
                            {index}
                          </TableCell>
                          <TableCell>
                            {mapTokenInfo[item.stTokenAddress].name}
                          </TableCell>
                          <TableCell>
                            {item.poolWeight}
                          </TableCell>
                          <TableCell>
                            {item.lastRewardBlock}
                          </TableCell>
                          <TableCell>
                            {item.lastRewardBlock + item.unstakeLockedBlocks}
                          </TableCell>
                          <TableCell>
                            {item.accRCCPerST}
                          </TableCell>
                          <TableCell>
                            {formatEther(item.stTokenAmount)}
                          </TableCell>
                          <TableCell>
                            {formatEther(item.minDepositAmount)}
                          </TableCell>
                          <TableCell>
                            <Box sx={{ display: 'flex', gap: '5px' }} >
                              <Button size='small' variant='contained' onClick={() => {
                                router.push('/stake/' + index)
                              }}>
                                stake
                              </Button>
                              <Button size='small' variant='contained' onClick={() => {
                                router.push('/withdraw/' + index)
                              }}>
                                withdraw
                              </Button>
                            </Box>

                          </TableCell>
                        </TableRow>
                      })
                    }
                  </TableBody>
                </Table>

              </Box> : <></>
            }
            <Button
              variant='contained' sx={{ mt: '20px' }} onClick={() => {
                setOpen(true)
              }}>增加池</Button>

            {/* <Button
              variant='contained' sx={{ mt: '20px' }} onClick={() => {
                writeContract({
                  address: ADDRESS_CONTRACT.RccStake,
                  abi: ABI_CONTRACT.RCCStake,
                  functionName: 'setStartBlock',
                  args: [
                    10
                  ]
                })
              }}>Test</Button> */}
          </Box>


          {
            open && <Dialog

              open={open}
              onClose={handleClose}
              slotProps={{
                paper: {
                  component: 'form',
                  onSubmit: (event: React.FormEvent<HTMLFormElement>) => {
                    event.preventDefault();
                    const formData = new FormData(event.currentTarget);
                    const formJson = Object.fromEntries((formData as any).entries());
                    if (!formJson.stTokenAddress) {
                      formJson.stTokenAddress = ADDRESS_CONTRACT.AddressZero
                    }
                    handleAddPool(formJson)
                  },
                },
              }}
            >
              <DialogTitle>新增池子</DialogTitle>
              <DialogContent>
                <DialogContentText>
                  当前池长度：{poolLength.data}
                </DialogContentText>
                <Box sx={{
                  mt: 2, display: 'flex', flexDirection: 'column', gap: '15px',
                  width: '500px'

                }}>
                  {
                    poolLength.data > 0 ? <FormControl fullWidth>
                      <InputLabel id="demo-simple-select-label">质押的代币(stTokenAddress)</InputLabel>
                      <Select
                        labelId="demo-simple-select-label"
                        id="stTokenAddress"
                        name="stTokenAddress"
                        label="质押的代币(stTokenAddress)"
                        value={defToken}
                        onChange={(e) => {
                          setDefToken(e.target.value)
                        }}
                      >
                        <MenuItem value={ADDRESS_CONTRACT.TokenA}>{mapTokenInfo[ADDRESS_CONTRACT.TokenA].name}</MenuItem>
                        <MenuItem value={ADDRESS_CONTRACT.TokenB}>{mapTokenInfo[ADDRESS_CONTRACT.TokenB].name}</MenuItem>
                      </Select>
                    </FormControl>
                      :
                      <TextField
                        required
                        id="stTokenAddress"
                        name="stTokenAddress"
                        label="质押的代币(stTokenAddress)"
                        fullWidth
                        disabled={poolLength.data == 0}
                        defaultValue={ADDRESS_CONTRACT.AddressZero}
                      />
                  }

                  <TextField
                    autoFocus
                    required
                    type='number'
                    id="poolWeight"
                    name="poolWeight"
                    label="池权重(poolWeight)影响最后RCC奖励分配"
                    fullWidth
                  />
                  <TextField
                    autoFocus
                    required
                    type='number'
                    id="minDepositAmount"
                    name="minDepositAmount"
                    label="最少质押金额(minDepositAmount)"
                    fullWidth
                    variant="standard"
                  />
                  <TextField
                    autoFocus
                    required
                    type='number'
                    id="unstakeLockedBlocks"
                    name="unstakeLockedBlocks"
                    label="unstakeLockedBlocks 多久可以提取(比如输入10，则10个区块内不可以提取)"
                    fullWidth
                    variant="standard"
                  />
                </Box>
              </DialogContent>
              <DialogActions>
                <Button onClick={handleClose}>Cancel</Button>
                <Button type="submit">Add</Button>
              </DialogActions>
            </Dialog>
          }
        </Box>
      </main>
    </div>
  );
};

export default Home;
