import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { ThemeProvider } from '@mui/material/styles';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { WagmiProvider } from 'wagmi';
import { config } from '../utils/wagmi';
import theme from '../utils/theme';
import Head from 'next/head';
import { RainbowKitProvider } from '@rainbow-me/rainbowkit';
import '@rainbow-me/rainbowkit/styles.css';
import { ToastContainer } from 'react-toastify';
import Layout from "@/components/Layout";

const client = new QueryClient();
export default function App({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>LanToken Stake</title>
      <meta
        content="generated by create next app"
        name="description"
      />
      <link href="/favicon.ico" rel="icon" />
    </Head>
    <ThemeProvider theme={theme}>
      <WagmiProvider config={config}>
        <QueryClientProvider client={client}>
          <RainbowKitProvider>
          <ToastContainer
                position="top-right"
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
              />
            <Layout><Component {...pageProps} /></Layout>              
          </RainbowKitProvider>
        </QueryClientProvider>
      </WagmiProvider>
    </ThemeProvider>
  </>
}
