import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import { Box, Button, Container, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, FormControl, FormLabel, InputLabel, MenuItem, Select, Snackbar, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useAccount, useBalance, useBlock, useBlockNumber, useReadContract, useReadContracts, useSimulateContract, useWriteContract } from 'wagmi';
import { ABI_CONTRACT, ADDRESS_CONTRACT } from '../utils/contractConfig'
import { parseEther, keccak256, toBytes, formatEther } from 'viem';
import { use, useMemo, useState } from 'react';
import { ToastContainer, toast } from 'react-toastify';

import { useRouter } from 'next/router';
import useGetERC20TokenInfo from '../hooks/useGetTokenInfo';
const ADMIN_ROLE = keccak256(toBytes("ADMIN_ROLE")); // 计算 ADMIN_ROLE 哈希值

const Home: NextPage = () => {
  const account = useAccount();
  const { data: currentBlockNumber } = useBlockNumber();
  
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <main>
         <Typography variant="h4">
          Welcome to RainbowKit + Next.js example
        </Typography>
      </main>
    </div>
  );
};

export default Home;
